#!/usr/bin/envpython3

"""
examples/identify_pii.py

End-to-end demonstration of the pii-identifier pipeline on synthetic HR documents generated by HRDocumentInjector.

Run with:
    python examples/identify_pii.py

Prerequisites:

pip install -e .
python -m spacy download en_core_web_sm
"""

from __future__ import annotations
import textwrap
from pii_identifier.injector import HRDocumentInjector
from pii_identifier.pipeline import PIIIdentifier
from pii_identifier.types import DetectionMethod

# ANSI color helpers

_RED = "\033[91m"
_BOLD = "\033[1m"
_DIM = "\033[2m"
_RESET = "\033[Om"
_CYAN = "\033[96m"
_GREEN = "\033[92m"
_YELLOW = "\033[93m"

def red(s: str) -> str:
    return f"{_RED}{s}{_RESET}"

def bold(s: str) -> str:
    return f"{_BOLD}{s}{_RESET}"

def dim(s: str) -> str:
    return f"{_DIM}{s}{_RESET}"

def cyan(s: str) - str:
    return f"{_CYAN}{s}{_RESET}"

def green(s: str) -> str:
    return f"{_GREEN}{s}{_RESET}"

def yellow(s: str) -> str:
    return f"{_YELLOW}{s}{_RESET}"

# Highlighting
def highlight_pii(text: str, matches) -> str: # type: ignore[type-arg]
    """Return the text with each PII span wrapped in red ANSI codes."""
    result = ""
    cursor = 0

    for match in sorted(matches, key=lambda m: m.start):
        result += text[cursor: match.start]
        result += red(text[match.start: match.end])
        cursor = match.end

    result += text[cursor:]
    return result

# Reporting Helpers
_COL_WIDTHS = [20, 30, 8, 10]
_HEADERS = ["PII Type", "Matched Text", "Method", "Confidence"]

def _truncate(s: str, max_len: int = 28) -> str:
    return s if len(s) <= max_len else s[:max_len - 1] + "_"

def _print_table(matches) -> None: # type: ignore [type-arg]
    header = " ".join(h.ljust(w) for h, w in zip(_HEADERS, _COL_WIDTHS))
    sep = " ".join("-" * w for w in _COL_WIDTHS)

    print(bold(header))
    print(dim(sep))
    
    for m in matches:
        method_label = (
            cyan("REGEX") if m.method == DetectionMethod.REGEX else yellow("NER")
        )

        row = [
            m.pii_type.ljust(_COL_WIDTHS[0]),
            _truncate(m.text).ljust(_COL_WIDTHS[1]),
            method_label.ljust(_COL_WIDTHS[2] + len(method_label) - 5),
            f"{m.confidence:.2f}".ljust(_COL_WIDTHS[3]),
        ]

        print(" ".join(row))

    print()

def _precision_recall(
    matches, ground_truth: list[dict]
) -> tuple[float, float]:
    """Compute token-level precision and recall against ground trust.
    
    A predicetd match is a true positive if it span overlaps with any 
    ground-truth entry of the same pii_type
    
    """

    def overlaps(m, gt) -> bool:
        return max(m.start, gt["start"]) < min(m.end, gt["end"])

    tp = sum(
        1
        for m in matches
        if any(
            overlaps(m, gt) and m.pii_type.value == gt["pii_type"]
            for gt in ground_truth
        )
    )

    precision = tp / len(matches) if matches else 0.0
    recall = tp / len(ground_truth) if ground_truth else 0.0

    return precision, recall

# Main

def main() -> None:
    injector = HRDocumentInjector(seed=42)
    identifier = PIIIdentifier(use_ner=True)

    doc_generators = [
        ("Offer Letter", injector.offer_letter),
        ("Employee Intake Form", injector.intake_form),
        ("Background Check Consent", injector.background_check_consent),
    ]

    aggregate_precision: list[float] = []
    aggregate_recall: list[float] = []

    for doc_name, generator in doc_generators:
        print("\n" + "=" * 70)
        print(bold(f" DOCUMENT: {doc_name}"))
        print("=" * 70)

        doc_text, ground_truth = generator()
        report = identifier.report(doc_text)
        matches = report["matches"]

        # ---- Highlighted original text ------
        print(bold("\n[Original text with PII highlighted in red]\n"))
        highlighted = highlight_pii(doc_text, matches)
        for line in highlighted.splitlines():
            print(" " + line)

        # -- Detection Table --
        print(bold(f"\n[Detected PII - {len(matches)} match(es)]\n"))
        if matches:
            _print_table(matches)
        else:
            print(dim("  (no PII detected)\n"))

        # -- Redacted preview --
        print(bold("[Redacted text preview]\n"))
        preview = textwrap.fill(report["redacted_text"], width=66)
        for line in preview.splitlines()[:8]: #show first 8 lines
            print(" " + dim(line))
        if len(report["redacted_text"].splitlines()) > 8:
            print(dim(" ..."))
        print()

        # -- Precision / Recall --
        precision, recall = _precision_recall(matches, ground_truth)
        aggregate_precision.append(precision)
        aggregate_recall.append(recall)

        print(bold("[Precision / Recall vs Ground Truth]\n"))
        gt_types = sorted({gt["pii_type"] for gt in ground_truth})
        print(f" Ground-truth PII types injected : {', '.join(gt_types)}")
        print(f" Detected types                  : {', '.join(report['pii_types_found'])}")
        print(f" Total injected PII values       : {len(ground_truth)}")
        print(f" Total detected matches          : {len(matches)}")
        p_color = green if precision >= 0.8 else yellow
        r_color = green if recall >= 0.8 else yellow
        print(f" Precision                       : {p_color(f'{precision:.1%}')}")
        print(f" Recall                          : {r_color(f'{recall:.1%}')}")


        # -- Aggregate summary --
        avg_precision = sum(aggregate_precision) / len(aggregate_precision)
        avg_recall = sum(aggregate_recall) / len(aggregate_recall)

        print("\n" + "=" * 70)
        print(bold("  AGGREGATE SUMMARY (3 documents)"))
        print("=" * 70)
        print(f" Documents processed        : {len(doc_generators)}")
        p_color = green if avg_precision >= 0.8 else yellow
        r_color = green if avg_recall >= 0.8 else yellow
        print(f" Average Precision          : {p_color(f'{avg_precision:.1%}')}")
        print(f" Average Recall             : {r_color(f'{avg_recall:.1%}')} ")
        print()
        print(
            dim(
                " Note: NER recall for person names and addresses varies with model.\n"
                " Swap en_core_web_sm -> en_core_web_lg for improved NER accuracy.\n"
            )
        )

if __name__ == "__main__":
    main()
